steps:
  # Pull the previous images for layer caching
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - 'docker pull gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest || exit 0'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}',
      '-f', '${_DOCKERFILE}',
      '--cache-from', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest',
      '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
      '.'
    ]
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest']

images: 
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'

substitutions:
  _SERVICE_NAME: data-sync
  _DOCKERFILE: Dockerfile.sync

options:
  machineType: 'E2_HIGHCPU_8'
  dynamic_substitutions: true
